version: "3.7"

services:
  br_explorehd_dvr:
    build: .
    container_name: blueos-br-explorehd-dvr
    network_mode: host
    ports:
      - "4444:4444"
    volumes:
      - /usr/blueos/extensions/br_explorehd_dvr:/app/recordings
    restart: unless-stopped
    environment:
      - BLUEOS=true
      - MCM_BASE=http://127.0.0.1:6020
